Remove preloader on load
Wicklets/wick-editor pull request #297
Opened 2020-12-02 21:05 UTC by sporklpony

The preloader now gets removed from DOM after the editor or a project is done loading.

2020-12-07 17:52 UTC, Luxapodular requested changes
Hey @sporklpony Thanks for reviewing this! I'm curious as to why there are two preloader removes (one in the index, one in the editor)? Is there a specific reason for this or is one of them superfluous?

I want to make sure we're not accidentally calling remove on an element that does not exist.

2020-12-07 19:56 UTC, sporklpony commented
One removes the preloader for the editor, and the other removes the preloader for exported projects. I'll double-check that both are necessary, but I'm 90% sure that this is the case.

2020-12-07 23:33 UTC, sporklpony commented
@Luxapodular I just double-checked and both removes do appear to be necessary, one for the editor and one for the exported zip (getting rid of one of the preloader removers results in a preloader not being removed). It seems that HTML export doesn't use the preloader, and as such there isn't a 3rd place the preloader needs to be removed.

2020-12-09 19:48 UTC, Luxapodular commented
Ah, right! Apologies, as this is some legacy code that even I got confused at. Nice work and thanks!

2020-12-09 20:43 UTC, closed without merging